# Metadata
sonar.projectKey=ThibaultPouch59200_LetMeCook_e204eff3-2106-40b9-b196-f98149d7a81c
sonar.projectName=LetMeCook

# Source information
sonar.sources=client/src,server
sonar.sourceEncoding=UTF-8
sonar.inclusions=**/*.js,**/*.vue
sonar.exclusions=**/node_modules/**,**/coverage/**,**/public/**,**/__tests__/**

# Tests
sonar.tests=server/__tests__
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=server/coverage/lcov.info